export const ActionTypes={
    FETCH_CATEGORIES:'FETCH_CATEGORIES',
    FETCH_CATEGORY:'FETCH_CATEGORY',
    SET_CATEGORIES:'SET_CATEGORIES',
    SELECTED_CATEGORY:'SELECTED_CATEGORY',
    REMOVE_SELECTED_CATEGORY:'REMOVE_SELECTED_CATEGORY',

    FETCH_CITIES:'FETCH_CITIES',
    FETCH_CITY:'FETCH_CITYY',
    SET_CITIES:'SET_CITIES',
    SELECTED_CITY:'SELECTED_CITY',
    REMOVE_SELECTED_CITY:'REMOVE_SELECTED_CITY',

    FETCH_PROFILES:'FETCH_PROFILES',
    FETCH_PROFILE:'FETCH_PROFILE',
    SET_PROFILES:'SET_PROFILES',
    SELECTED_PROFILE:'SELECTED_PROFILE',
    REMOVE_SELECTED_PROFILE:'REMOVE_SELECTED_PROFILE',


    FETCH_ZONES:'FETCH_ZONES',
    FETCH_ZONE:'FETCH_ZONE',
    SET_ZONES:'SET_ZONES',
    SELECTED_ZONE:'SELECTED_ZONE',
    REMOVE_SELECTED_ZONE:'REMOVE_SELECTED_ZONE',

}
